version: '3.8'

services:
  backend:
    build: ./backend
    container_name: plastic_press_backend
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - TZ=Asia/Yangon
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: plastic_press_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: plastic_press_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Asia/Yangon
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  postgres_data:
