"""initial

Revision ID: b06367720b50
Revises: 
Create Date: 2026-04-15 01:36:27.335146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06367720b50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'payment_method',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('CASH', 'BANK_TRANSFER', 'KBZPAY', name='paymentmethod'),
               nullable=False)
    op.alter_column('voucher', 'payment_method',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('CASH', 'BANK_TRANSFER', 'KBZPAY', name='paymentmethod'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voucher', 'payment_method',
               existing_type=sa.Enum('CASH', 'BANK_TRANSFER', 'KBZPAY', name='paymentmethod'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('payment', 'payment_method',
               existing_type=sa.Enum('CASH', 'BANK_TRANSFER', 'KBZPAY', name='paymentmethod'),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
